#!/bin/bash

export dotfiles="$HOME/dotfiles"

ln -sf $dotfiles/vim/vimrc             $HOME/.vimrc
ln -sf $dotfiles/vim/vim               $HOME/.vim

ln -sf $dotfiles/bashrc                $HOME/.bashrc
ln -sf $dotfiles/git/gitconfig         $HOME/.gitconfig
ln -sf $dotfiles/git/gitignore         $HOME/.gitignore
ln -sf $dotfiles/tmux.conf             $HOME/.tmux.conf

rm $HOME/.vim/vim
